eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceurl:
      defaultZone: http://localhost:8300/eureka/

zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8301
    stock-service:
      path: /stock-service/**
      url: http://localhost:8302
